### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by chanserv** [bsblabs/talend-job-exporter#1]
Hi,

I'm looking to build the project under eclipse, everything looks fine, but i can't find org.talend.core.model and org.talend.core.commons.runtime to satisfy pom.xml requirements list.
Even on the web, we still can't find any file.

Thanks in advance.

**Comment by sebge2** [comment]
Hello,

If I remember I have manually install those dependencies from my local talend installation, in the Eclipse directory.

**Comment by chanserv** [comment]
Which talend version contain those files. I can't find them in open studio 6.1

**Comment by belaazim** [comment]
Hello,
 Two dependencies are not available on Talend Open Studio (6.1.0 or 5.5.1):
- org.talend.core.model
- org.talend.core.commons.runtime
  Where could we get these two dependencies to make the build of the talend-job-exporter code successful ?
  Thanks in advance,

**Comment by grzr** [comment]
Before compiling I had to add dependency in pom.xml for
- org.eclipse.emf.ecore.

I've tried to build against talend version 5.5.1 and 5.5.2 and for both versions I've compiling error:
talend-job-exporter/src/main/java/com/bsb/tools/talend/export/Workspace.java:[134,53] error: cannot access Notifier.

@sebge2 have you encounter such problem?

**Comment by DaKaLKa** [comment]
Please take a look at my fork - it adds some new features and is based on talend 6.1.1

**Comment by sebge2** [comment]
Merged :)
